CREATE DATABASE IF NOT EXISTS tictactoe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE tictactoe;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS games (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player1 INT UNSIGNED DEFAULT NULL,
  player2 INT UNSIGNED DEFAULT NULL,
  board VARCHAR(9) DEFAULT '---------',
  turn INT UNSIGNED DEFAULT NULL,
  winner INT DEFAULT NULL,
  FOREIGN KEY (player1) REFERENCES users(id),
  FOREIGN KEY (player2) REFERENCES users(id)
);


